### ISSUE TITLE
stopped working... :(

### ISSUE THREAD

**Issue by bronestly** [gubler/gitbook-plugin-callouts#5]
Hey there

plugin is successfully loaded, yet styles are not applied.
Can I give you access to the private book to have a look?

Build log:

```
Downloading source
Extracting source
GitBook version is 3.0.3 
Tweaking book.json
Installing plugins
info: installing 4 plugins using npm@3.9.2 
info:  
info: installing plugin "callouts" 
info: install plugin "callouts" (*) from NPM with version 0.0.10 
/tmp/book
└─┬ gitbook-plugin-callouts@0.0.10 
  └─┬ cheerio@0.19.0 
    ├─┬ css-select@1.0.0 
    │ ├── boolbase@1.0.0 
    │ ├── css-what@1.0.0 
    │ ├── domutils@1.4.3 
    │ └── nth-check@1.0.1 
    ├─┬ dom-serializer@0.1.0 
    │ └── domelementtype@1.1.3 
    ├── entities@1.1.1 
    ├─┬ htmlparser2@3.8.3 
    │ ├── domelementtype@1.3.0 
    │ ├── domhandler@2.3.0 
    │ ├── domutils@1.5.1 
    │ ├── entities@1.0.0 
    │ └─┬ readable-stream@1.1.14 
    │   ├── core-util-is@1.0.2 
    │   ├── inherits@2.0.1 
    │   ├── isarray@0.0.1 
    │   └── string_decoder@0.10.31 
    └── lodash@3.10.1 

info: >> plugin "callouts" installed with success 
info:  
info: installing plugin "image-captions" 
info: install plugin "image-captions" (*) from NPM with version 0.4.1 
/tmp/book
├── gitbook-plugin-callouts@0.0.10 
└─┬ gitbook-plugin-image-captions@0.4.1 
  ├─┬ cheerio@0.20.0 
  │ ├─┬ css-select@1.2.0 
  │ │ ├── css-what@2.1.0 
  │ │ └── domutils@1.5.1 
  │ ├─┬ jsdom@7.2.2 
  │ │ ├── abab@1.0.3 
  │ │ ├── acorn@2.7.0 
  │ │ ├── acorn-globals@1.0.9 
  │ │ ├── cssom@0.3.1 
  │ │ ├── cssstyle@0.2.36 
  │ │ ├─┬ escodegen@1.8.0 
  │ │ │ ├── esprima@2.7.2 
  │ │ │ ├── estraverse@1.9.3 
  │ │ │ ├── esutils@2.0.2 
  │ │ │ ├─┬ optionator@0.8.1 
  │ │ │ │ ├── deep-is@0.1.3 
  │ │ │ │ ├── fast-levenshtein@1.1.3 
  │ │ │ │ ├── levn@0.3.0 
  │ │ │ │ ├── prelude-ls@1.1.2 
  │ │ │ │ ├── type-check@0.3.2 
  │ │ │ │ └── wordwrap@1.0.0 
  │ │ │ └─┬ source-map@0.2.0 
  │ │ │   └── amdefine@1.0.0 
  │ │ ├── nwmatcher@1.3.7 
  │ │ ├── parse5@1.5.1 
  │ │ ├─┬ request@2.72.0 
  │ │ │ ├── aws-sign2@0.6.0 
  │ │ │ ├── aws4@1.4.1 
  │ │ │ ├─┬ bl@1.1.2 
  │ │ │ │ └─┬ readable-stream@2.0.6 
  │ │ │ │   ├── isarray@1.0.0 
  │ │ │ │   ├── process-nextick-args@1.0.7 
  │ │ │ │   └── util-deprecate@1.0.2 
  │ │ │ ├── caseless@0.11.0 
  │ │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ │ └── delayed-stream@1.0.0 
  │ │ │ ├── extend@3.0.0 
  │ │ │ ├── forever-agent@0.6.1 
  │ │ │ ├─┬ form-data@1.0.0-rc4 
  │ │ │ │ └── async@1.5.2 
  │ │ │ ├─┬ har-validator@2.0.6 
  │ │ │ │ ├─┬ chalk@1.1.3 
  │ │ │ │ │ ├── ansi-styles@2.2.1 
  │ │ │ │ │ ├── escape-string-regexp@1.0.5 
  │ │ │ │ │ ├─┬ has-ansi@2.0.0 
  │ │ │ │ │ │ └── ansi-regex@2.0.0 
  │ │ │ │ │ ├── strip-ansi@3.0.1 
  │ │ │ │ │ └── supports-color@2.0.0 
  │ │ │ │ ├─┬ commander@2.9.0 
  │ │ │ │ │ └── graceful-readlink@1.0.1 
  │ │ │ │ ├─┬ is-my-json-valid@2.13.1 
  │ │ │ │ │ ├── generate-function@2.0.0 
  │ │ │ │ │ ├─┬ generate-object-property@1.2.0 
  │ │ │ │ │ │ └── is-property@1.0.2 
  │ │ │ │ │ ├── jsonpointer@2.0.0 
  │ │ │ │ │ └── xtend@4.0.1 
  │ │ │ │ └─┬ pinkie-promise@2.0.1 
  │ │ │ │   └── pinkie@2.0.4 
  │ │ │ ├─┬ hawk@3.1.3 
  │ │ │ │ ├── boom@2.10.1 
  │ │ │ │ ├── cryptiles@2.0.5 
  │ │ │ │ ├── hoek@2.16.3 
  │ │ │ │ └── sntp@1.0.9 
  │ │ │ ├─┬ http-signature@1.1.1 
  │ │ │ │ ├── assert-plus@0.2.0 
  │ │ │ │ ├─┬ jsprim@1.2.2 
  │ │ │ │ │ ├── extsprintf@1.0.2 
  │ │ │ │ │ ├── json-schema@0.2.2 
  │ │ │ │ │ └── verror@1.3.6 
  │ │ │ │ └─┬ sshpk@1.8.3 
  │ │ │ │   ├── asn1@0.2.3 
  │ │ │ │   ├── assert-plus@1.0.0 
  │ │ │ │   ├─┬ dashdash@1.14.0 
  │ │ │ │   │ └── assert-plus@1.0.0 
  │ │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │ │   ├─┬ getpass@0.1.6 
  │ │ │ │   │ └── assert-plus@1.0.0 
  │ │ │ │   ├── jodid25519@1.0.2 
  │ │ │ │   ├── jsbn@0.1.0 
  │ │ │ │   └── tweetnacl@0.13.3 
  │ │ │ ├── is-typedarray@1.0.0 
  │ │ │ ├── isstream@0.1.2 
  │ │ │ ├── json-stringify-safe@5.0.1 
  │ │ │ ├─┬ mime-types@2.1.11 
  │ │ │ │ └── mime-db@1.23.0 
  │ │ │ ├── node-uuid@1.4.7 
  │ │ │ ├── oauth-sign@0.8.2 
  │ │ │ ├── qs@6.1.0 
  │ │ │ ├── stringstream@0.0.5 
  │ │ │ └── tunnel-agent@0.4.3 
  │ │ ├── sax@1.2.1 
  │ │ ├── symbol-tree@3.1.4 
  │ │ ├── tough-cookie@2.2.2 
  │ │ ├── webidl-conversions@2.0.1 
  │ │ ├─┬ whatwg-url-compat@0.6.5 
  │ │ │ └── tr46@0.0.3 
  │ │ └── xml-name-validator@2.0.1 
  │ └── lodash@4.13.1 
  ├── q@1.4.1 
  └── semver@5.1.0 

info: >> plugin "image-captions" installed with success 
info:  
info: installing plugin "emphasize" 
info: install plugin "emphasize" (*) from NPM with version 1.1.0 
/tmp/book
├── gitbook-plugin-callouts@0.0.10 
├── gitbook-plugin-emphasize@1.1.0 
└── gitbook-plugin-image-captions@0.4.1 

info: >> plugin "emphasize" installed with success 
info:  
info: installing plugin "comment" 
info: install plugin "comment" (*) from NPM with version 1.0.2 
/tmp/book
├── gitbook-plugin-callouts@0.0.10 
├── gitbook-plugin-comment@1.0.2 
├── gitbook-plugin-emphasize@1.1.0 
└── gitbook-plugin-image-captions@0.4.1 

info: >> plugin "comment" installed with success 
Building Site, will upload
info: 10 plugins are installed 
info: loading plugin "callouts"... OK 
info: loading plugin "image-captions"... OK 
info: loading plugin "emphasize"... OK 
info: loading plugin "comment"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 30 pages 
info: found 40 asset files 
warn: "options" property is deprecated, use config.get(key) instead 
warn: "sections" property is deprecated, use page.content instead 
info: >> generation finished with success in 4.1s ! 
Site built, uploading now
awscli succeeded :)
Upload finished
```

**Comment by gubler** [comment]
Sorry for taking so long to reply, this month has been busy and I'm about to leave town for two weeks. I won't have a chance to look into this until I get back early August.

At first glance, I'm going to guess this is a compatibility problem with Gitbook 3. The plugin currently works with Gitbook 2 and I hadn't seen v3 had been released. I will look into this when I get back in town.

**Comment by aschempp** [comment]
The problem seems to be that `page.sections` is no longer supported. The console says to use `page.content` instead. Would be great to have a fix :)

**Comment by gubler** [comment]
Thank you very much @aschempp! I've merged in the fix and released v0.1.1.

**Comment by nagim** [comment]
It only works with Markdown, still not working with AsciiDoc.

**Comment by gubler** [comment]
I will take a look at it as soon as I get some time.

**Comment by gubler** [comment]
@nagim Can you share an example AsciiDoc file that isn't working. I made a really simple test document and the callout was generated correctly. I'm betting it's just the simplicity of the test document I created and I'd like to see some code that doesn't render correctly.

Sorry for taking so long to look at this.

**Comment by nagim** [comment]
Thanks for the follow-up. Must have been some interim glitch, as it's working for me again, too.
Thanks a lot, you can close this. :+1:

**Comment by gubler** [comment]
Awesome - thanks for the fast response :)
